"""empty message

Revision ID: 37526e3fe569
Revises: 0f59ff4f9d1d
Create Date: 2026-01-10 12:57:47.948243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37526e3fe569'
down_revision = '0f59ff4f9d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
