"""empty message

Revision ID: 415214670ad5
Revises: 6edae3927b1f
Create Date: 2026-01-14 20:41:17.571599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415214670ad5'
down_revision = '6edae3927b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_monitor',
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tg_user.id'], ),
    sa.PrimaryKeyConstraint('tg_user_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_monitor')
    op.drop_table('tg_user')
    # ### end Alembic commands ###
