"""empty message

Revision ID: 6edae3927b1f
Revises: 37526e3fe569
Create Date: 2026-01-13 13:40:37.290492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edae3927b1f'
down_revision = '37526e3fe569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tg', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_column('is_tg')

    # ### end Alembic commands ###
