"""empty message

Revision ID: 8813ce6d2268
Revises: 415214670ad5
Create Date: 2026-01-15 09:06:45.956401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8813ce6d2268'
down_revision = '415214670ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_client_name'), ['name'])

    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_command_tg_user_id_tg_user'), 'tg_user', ['tg_user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_command_tg_user_id_tg_user'), type_='foreignkey')
        batch_op.drop_column('tg_user_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_client_name'), type_='unique')

    # ### end Alembic commands ###
