"""empty message

Revision ID: d0f2eb3ff629
Revises: 8813ce6d2268
Create Date: 2026-01-18 16:17:21.554565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f2eb3ff629'
down_revision = '8813ce6d2268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tg_user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
